### PR TITLE
Conversion to new NIST format

### PR DESCRIPTION
**Pull request by ronaldtse**
Temporary PR to convert to new NIST format.

This requires metanorma/metanorma-nist#258 to be implemented.

### CODE REVIEW

**Comment by ronaldtse** [comment]
This PR is soon ready. Implementation of the new document type that works with ACVP has been completed.

The only remaining issues are:
* metanorma/metanorma-nist#268 (when DOI not specified, do not show link on cover)
* metanorma/metanorma-nist#269 (issue with missing wrapping brackets on non-auto-fetched references)

@CAMOBAP can you help fix the docker image and get this PR passing? Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP the latest metanorma-cli has been released. Please ping me when this issue is done. Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse the fix was in `metanorma` gem not in `metanorma-cli` gem. In Gemfile for docker we getting only metanorma-cli from master https://github.com/metanorma/metanorma-docker/blob/master/mn/Gemfile.in

Should we add `metanorma` from github too?

**Comment by ronaldtse** [comment]
I thought @opoudjis already released the metanorma gem again?

**Comment by ronaldtse** [comment]
@CAMOBAP we should not be needing any Git gems.

**Comment by CAMOBAP** [comment]
@ronaldtse one more issue discovered in the scope of this PR https://github.com/metanorma/metanorma/pull/158

As a temporal workaround, I have added `fontist update`

**Comment by ronaldtse** [comment]
We want to use `metanorma site generate` for GHA testing.

**Comment by CAMOBAP** [comment]
@ronaldtse migrated to sitegen, could you please review

**Comment by CAMOBAP** [comment]
ping @ronaldtse ronaldtse

**Pull request merged**
